---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - config.alloc.nephio.org
  resources:
  - networks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.alloc.nephio.org
  resources:
  - networks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - inv.nephio.org
  resources:
  - targets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - inv.nephio.org
  resources:
  - targets/status
  verbs:
  - get
  - patch
  - update
